Fix bug of sfixMatrix.__mul__()
sfixMatrix * some_array will throw this error

```
Traceback (most recent call last):
  File "./compile.py", line 88, in <module>
    main()
  File "./compile.py", line 85, in main
    compilation()
  File "./compile.py", line 72, in compilation
    assemblymode=options.assemblymode, debug=options.debug)
  File "/root/mpc/MP-SPDZ/Compiler/compilerLib.py", line 57, in run
    execfile(prog.infile, VARS)
  File "/root/mpc/MP-SPDZ/Programs/Source/cotton2.mpc", line 18, in <module>
    mul_result = A * t
  File "/root/mpc/MP-SPDZ/Compiler/types.py", line 2688, in __mul__
    assert len(other) == self.sizes[1]
AttributeError: 'sfixMatrix' object has no attribute 'sizes'
```

I guess that's because `self` now points to sfixMatrix while `__mul__` is using its super-class Matrix's.